# Generated by Django 4.2 on 2023-05-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=45)),
                ('Descripcion', models.TextField()),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.categorias')),
            ],
        ),
    ]
