# Generated by Django 4.2 on 2023-05-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
    ]
