# Generated by Django 4.2 on 2023-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0002_noticia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
