# Generated by Django 4.2 on 2023-05-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0003_noticia_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
