# Generated by Django 4.2 on 2023-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0008_noticia_comentario_noticia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='comentario',
            field=models.CharField(blank=True, default='Motivo Desconocido', max_length=200),
        ),
    ]
