# Generated by Django 4.2.2 on 2023-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0012_alter_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
