# Generated by Django 4.2.2 on 2023-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0013_perfilusuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
