# Generated by Django 4.2.2 on 2023-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0014_perfilusuario_ciudad_perfilusuario_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
