# Generated by Django 4.2.2 on 2023-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0015_perfilusuario_descripcion_perfilusuario_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
